name: SwagLabs Web Store Pipeline

on:
  push:
    branches: 
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore            
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Run Tests and Generate Test Report
        run: |
          mkdir -p Reports
          dotnet test --logger "junit;LogFilePath=Reports/test-results.xml" --verbosity normal
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: SwagLabsProject/Reports/test-results.xml 

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Tests
          path: SwagLabsProject/Reports/test-results.xml
          reporter: jest-junit

      